sudo: required
dist: trusty
language: c
services:
  - docker

before_install:
  # pull before running make so we can use intermediate layers as cache
  - sudo docker pull welder/fedora:latest

script:
  - make weld-fedora

after_success:
  - |
        if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            docker login -u atodorov -p $DOCKER_PASSWORD
            docker push welder/fedora
        fi

notifications:
  email:
    on_failure: change
    on_success: never

env:
  global:
    secure: "Sl2qmIyXvzZN4cRFpR9h7rPcasO0YNyV3UarKmtC8Nbhp8So5bLlxrO0EhvkdW/bdctqLxmJsyTsrIFAWhh85EdUYBtcJ8qAEifRbNHnxiG5wG+cuVMYHjtcpBNeWICRxL2ZlNlCdrjiReGeR2B6MLL6H9hAM0vWFGxjz865aa6hVmLkP9TqBN5clqhXvBrt31EtQ7G9z4v8OEwhM1mlMdkOB0BGIufXUMI9YGS08pkunojHXI3+P39LBmZPprV3ovfhY+q1c94QUDVxyoRpVXQKxBXWaHtaFCGv/Td9PYn6Fu/kyyvS+9gPIjUoXLI8B56OCILcGo7cy2uPxRxXWnJ7pBBdAGF1nJiGdYR5bw7IkrRuUqiRewwyPvm/NBKSITkjt02L+6hKsqCDiqKfK6q/IoIjd0oIaG4Bqlpe3AWKjkNj/vuHep0E7kHHSFaACXRQw3spZNMNhAB0ZtwA4DGmt2pcVuuMbv1yaUJyO67FEh0wBskgANvK5ANmbcd7mpTVJxNEBdsmqVeVNHsSsD1fMm/PCiAu3udEcOYQw2R6c9xly6FqVeOt39NVLZGP2KLp5f3s1ubPuMezhIsDbHsMpsERNDNKr423y8I4DFXK0zkGKnKFKY3g9SkHyWe3Q5ICH6bfnnffkGRbaI7+njYtHBmllBCRCHid0sgrRB8="
